#!/usr/bin/env python3
"""Extract the 5x7 font of telem.c (/home/ubuntu/psp/telem/telem.c:73-133,
ASCII 32..90) into a C header for the volume harness's screen OCR.

The OCR reads the HUD back from the simulated framebuffer pixels. It uses
telem.c's table, not pscol.c's copy (pscol.c:2479-2510), so the screen record
does not depend on the code under test. The script also reports whether the
two tables are identical (a difference would itself be a finding).

Usage: font_from_telem.py TELEM_C PSCOL_C OUT_H
"""
import re
import sys


def table(path, start_pat):
    src = open(path, encoding="latin-1").read()
    i = src.index(start_pat)
    j = src.index("};", i)
    rows = re.findall(r"\{((?:\s*0x[0-9A-Fa-f]{2}\s*,?){7})\}", src[i:j])
    out = [[int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{2}", r)] for r in rows]
    if len(out) != 59 or any(len(r) != 7 for r in out):
        raise SystemExit("%s: expected 59 rows of 7 bytes, got %d" % (path, len(out)))
    return out


def main():
    telem_c, pscol_c, out_h = sys.argv[1:4]
    t = table(telem_c, "static const unsigned char FONT[59][7]")
    p = table(pscol_c, "static const unsigned char FONT[59][7]")
    same = (t == p)
    with open(out_h, "w") as f:
        f.write("/* generated by font_from_telem.py from %s (ASCII 32..90) */\n" % telem_c)
        f.write("/* telem.c table identical to pscol.c table: %s */\n" % ("yes" if same else "NO"))
        f.write("static const unsigned char TELEM_FONT[59][7] = {\n")
        for k, r in enumerate(t):
            f.write("\t{%s}, /* %r */\n" % (",".join("0x%02X" % b for b in r), chr(32 + k)))
        f.write("};\n")
    print("font: 59 glyphs from %s; identical to pscol.c table: %s" % (telem_c, "yes" if same else "NO"))
    return 0 if same else 1


if __name__ == "__main__":
    sys.exit(main())
