#!/usr/bin/env python3
"""Emit banner.c: linux_banner with the exact bytes of the packaged build's
banner.txt (BUILD/banner.txt), and check its zlib CRC-32 against
BUILD/build_id.txt (DESIGN 1.7 word 2, R-4)."""
import sys, zlib
banner = open(sys.argv[1], 'rb').read()
want = int(open(sys.argv[2]).read().strip(), 16)
crc = zlib.crc32(banner) & 0xFFFFFFFF
if crc != want:
    sys.exit("banner CRC %08x != build_id %08x" % (crc, want))
lit = ''.join('\\x%02x' % b for b in banner)
sys.stdout.write('/* generated by tools/mkbanner.py from %s; CRC-32 0x%08x */\n' % (sys.argv[1], crc))
sys.stdout.write('const char linux_banner[] = "%s";\n' % lit)
